route:
  receiver: webhook-logger
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 30m

receivers:
  - name: webhook-logger
    webhook_configs:
      - url: http://alert-logger:5001/alert
        send_resolved: true
